image: docker:27

services:
  - docker:27-dind

stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ''
  IMAGE_NAME: registry.gitlab.com/e4e-webdev/msdat

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin

# --------------------
# BUILD IMAGE (develop)
# --------------------
build_develop:
  stage: build
  only:
    - develop
  variables:
    IMAGE_TAG: develop
  script:
    - cp "$staging_env" .env
    - export $(grep -v '^#' .env | xargs)

    - |
      docker build \
        --build-arg VUE_APP_API_BASE_URL="$VUE_APP_API_BASE_URL" \
        --build-arg VUE_APP_API_LOGIN_URL="$VUE_APP_API_LOGIN_URL" \
        --build-arg VUE_APP_API_GPT_URL="$VUE_APP_API_GPT_URL" \
        --build-arg VUE_APP_FRONTEND_KEY_ID="$VUE_APP_FRONTEND_KEY_ID" \
        --build-arg VUE_APP_FRONTEND_AUTH="$VUE_APP_FRONTEND_AUTH" \
        -t $IMAGE_NAME:$IMAGE_TAG .

    - docker push $IMAGE_NAME:$IMAGE_TAG

# --------------------
# DEPLOY (develop)
# --------------------
deploy_develop:
  stage: deploy
  only:
    - develop
  variables:
    IMAGE_TAG: develop
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$MSDATDEVELOP" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - |
      ssh -p 3322 e4esysadmin@208.87.128.190 "
        docker pull $IMAGE_NAME:$IMAGE_TAG &&
        docker-compose -f /srv/msdat-develop/docker-compose.yml up -d --remove-orphans
      "

# ====================
# BUILD IMAGE (master)
# ====================
build_master:
  stage: build
  only:
    - master
  variables:
    IMAGE_TAG: latest
  script:
    - cp "$master_env" .env
    - export $(grep -v '^#' .env | xargs)

    - |
      docker build \
        --build-arg VUE_APP_API_BASE_URL="$VUE_APP_API_BASE_URL" \
        --build-arg VUE_APP_API_LOGIN_URL="$VUE_APP_API_LOGIN_URL" \
        --build-arg VUE_APP_API_GPT_URL="$VUE_APP_API_GPT_URL" \
        --build-arg VUE_APP_FRONTEND_KEY_ID="$VUE_APP_FRONTEND_KEY_ID" \
        --build-arg VUE_APP_FRONTEND_AUTH="$VUE_APP_FRONTEND_AUTH" \
        -t $IMAGE_NAME:$IMAGE_TAG .

    - docker push $IMAGE_NAME:$IMAGE_TAG

# ====================
# DEPLOY (master)
# ====================
deploy_master:
  stage: deploy
  only:
    - master
  when: manual
  variables:
    IMAGE_TAG: latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$MSDATMASTER" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - |
      ssh -p 3322 e4esysadmin@172.93.48.4 "
        docker pull $IMAGE_NAME:$IMAGE_TAG &&
        docker-compose -f /srv/msdat/docker-compose.yml up -d --remove-orphans
      "
